# Lab 01 - Wstęp do ML, podział danych

## Trochę wstępu na początek

### Czym jest Machine Learning (ML)?

**Machine Learning (Uczenie Maszynowe)** to dziedzina sztucznej inteligencji (AI), która koncentruje się na tworzeniu algorytmów i modeli, które mogą samodzielnie uczyć się na podstawie danych. Celem ML jest wykorzystanie danych do prognozowania, klasyfikacji, wykrywania wzorców i podejmowania decyzji bez potrzeby programowania reguł na sztywno. Modele ML uczą się na podstawie przykładów i wzorców, zamiast stosować twarde reguły, co pozwala im działać efektywnie w dynamicznych i skomplikowanych środowiskach.

Przykładowe zastosowania ML to:
- Rozpoznawanie obrazów i dźwięków,
- Systemy rekomendacyjne (np. Netflix, Amazon),
- Wykrywanie oszustw (fraud detection, spam detection),
- Modele prognozujące np. ceny akcji czy zachowania użytkowników.

### Analiza Danych w Machine Learning

**Analiza Danych** w kontekście Machine Learning jest kluczowym procesem, który polega na przygotowaniu, eksploracji i interpretacji danych, na których model ML będzie się uczył. Proces ten jest ważny, ponieważ jakość danych bezpośrednio wpływa na efektywność modelu. Analiza danych obejmuje kilka istotnych kroków:

1. **Zbieranie Danych**: Dane są sercem każdego modelu ML. Mogą pochodzić z różnych źródeł, takich jak bazy danych, pliki CSV, strumienie danych z czujników itp.
   
2. **Czyszczenie Danych**: Dane często zawierają braki, błędy lub niespójności. Proces czyszczenia obejmuje usuwanie brakujących wartości, eliminację duplikatów oraz korektę błędów w danych.

3. **Eksploracja Danych**: Przed stworzeniem modelu konieczne jest zrozumienie danych. Eksploracja obejmuje wizualizację danych, analizę rozkładów zmiennych, identyfikację zależności między cechami oraz wyszukiwanie anomalii.

4. **Inżynieria Cech (Feature Engineering)**: Ważnym etapem jest przekształcenie surowych danych w cechy (ang. features), które będą używane przez model ML. Obejmuje to tworzenie nowych cech na podstawie istniejących, standaryzację, normalizację, kodowanie zmiennych kategorialnych itp.

5. **Podział Danych**: Dane dzielimy na zbiory treningowe, walidacyjne i testowe, aby ocenić, jak dobrze model generalizuje się na nowych, niewidzianych wcześniej danych.

6. **Analiza wyników**: Po trenowaniu modelu, analiza wyników (na przykład analiza metryk takich jak dokładność, precyzja, czułość) pozwala ocenić, jak dobrze model radzi sobie z zadaniem.

### Znaczenie Analizy Danych w ML

W ML jakość danych i sposób ich przetwarzania ma kluczowe znaczenie. Nawet najlepsze algorytmy nie będą działały prawidłowo, jeśli dane będą nieodpowiednio przygotowane. Dlatego analiza danych stanowi niezbędny element całego procesu budowy modeli ML.

Proces Machine Learning z zaawansowaną analizą danych jest wykorzystywany w różnych branżach, m.in. w finansach, marketingu, medycynie czy inżynierii.

Cały proces obróbki danych przed dopuszczeniem ich do modelu jest bardzo czxęsto najbardziej czasochłonnym i złożonym zestawem opracji w trakcie tworzenia modelu... Dlatego zacznijmy od czegoś łatwego.

## Podział danych

W procesie uczenia maszynowego (ML) dane są zazwyczaj dzielone na różne zbiory w celu trenowania, walidacji i testowania modeli. Oto najczęstsze przykłady podziału danych:

### 1. **Podział na zbiór treningowy i testowy (Train-Test Split)**

Najprostszy i najczęściej stosowany podział, w którym dane dzieli się na dwa zbiory:
- **Zbiór treningowy (Training Set)**: Służy do trenowania modelu. Model uczy się na tych danych, analizując wzorce i zależności.
- **Zbiór testowy (Test Set)**: Wykorzystywany do oceny modelu po zakończeniu treningu, aby sprawdzić, jak dobrze generalizuje na nowych, niewidzianych wcześniej danych.

Typowy podział to **80% danych na trening i 20% na test**, choć wartości te mogą się różnić (np. 70/30 lub 90/10), w zależności od rozmiaru dostępnych danych. W skrajnej sytuacji, gdy mamy mało danych podział 90/10 może zaskutkować, że w zbiorze treningowym będziemy mieli jedynie jeden rekord, co w praktyce daj nam tylko dwie możliwości: 100% poprawności działania modelu bądź 0%. Oczywiście unikamy takich sytuacji, dlatego ważne jest odpowiednie dobranie podziału danych jednocześnie dążać do jak największej ilości danych (zważając również na ich jakość).

### 2. **Podział na zbiór treningowy, walidacyjny i testowy (Train-Validation-Test Split)**

Aby uzyskać bardziej precyzyjną ocenę modelu i zoptymalizować jego hiperparametry, wprowadza się dodatkowy zbiór:
- **Zbiór treningowy (Training Set)**: Używany do trenowania modelu.
- **Zbiór walidacyjny (Validation Set)**: Służy do optymalizacji hiperparametrów oraz wyboru najlepszego modelu. Dane te są używane do testowania modelu w trakcie trenowania, ale nie są wykorzystywane bezpośrednio w uczeniu.
- **Zbiór testowy (Test Set)**: Używany do ostatecznej oceny modelu po zakończeniu jego trenowania.

Typowy podział to np. **70% trening, 15% walidacja i 15% test**, ale wartości mogą się różnić w zależności od ilości danych.

Można z łatwością dokonać manualnej implementacji funkcji/metody odpowiedzialnej za dokonanie podziału, lecz znacznie lepszą drogą będzie wykorzystanie dostępnych (i przetestowanych) implementacji dostarczanych za pomocą bibliotek.

### Scikit-learn

Biblioteka [scikit-learn](https://pypi.org/project/scikit-learn/) jest jednym z najczęściej stosowanych pakietów przez badaczy danych. Scikit-learn nie wchodzi w skład biblioteki standardowej, zatem trzeba ją doinstalować manualnie. W przypadku korzystania ze środowisk Colab lub Conda, implementacja zwykle jest już zainstalowana automatycznie w każdym nowym środowisku roboczym.

Biblioteka scikit-learn - oprócz implementacji funkcji służących do podziału danych - dostarcza także metody przetwarzania i uzupełniania informacji, a także implementacje popularnych algorytmów uczenia maszynowego. Ciekawą funkcjonalnością biblioteki scikit-learn jest zautomatyzowane udostępnianie popularnych (rzeczywistych) zbiorów danych bez konieczności ich manualnego pobierania i rozpakowywania. Pełna lista dostępna jest pod adresem: [https://scikit-learn.org/stable/datasets.html](https://scikit-learn.org/stable/datasets.html).

## Pobieranie danych za pomocą biblioteki scikit-learn

Do pobierania zbiorów danych przeznaczone są funkcje sprecyzowane w podstronach poświęconych każdemu ze zbiorów. Przykładowo, dla zbioru California Housing ([https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset)) przeznaczona jest funkcja fetch_california_housing dostępna w module *datasets* pakietu *sklearn*.

Domyślnie zwracany jest słownik zawierający tablice wartości będące atrybutami. Przekazując do funkcji parametr *as_frame* o wartości logicznej *True*, zostanie zwrócony zbiór danych w postaci ramki danych *pandas* dostępne w kluczu *frame* wynikowego słownika.

In [1]:
from sklearn.datasets import fetch_california_housing

In [14]:
data = fetch_california_housing(as_frame=True)['frame']
data

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [15]:
data.head(10)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5  4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
6  3.6591      52.0  4.931907   0.951362      1094.0  2.128405     37.84   
7  3.1200      52.0  4.797527   1.061824      1157.0  1.788253     37.84   
8  2.0804      42.0  4.294118   1.117647      1206.0  2.026891     37.84   
9  3.6912      52.0  4.970588   0.990196      1551.0  2.172269     37.84   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422  
5    -122.25        2.697  
6    -122.25        2.992  
7    -122.25        2.414  
8    -122.26        2.267  
9    -122.25        2.611

In [4]:
data.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')

In [5]:
data.dtypes

MedInc         float64
HouseAge       float64
AveRooms       float64
AveBedrms      float64
Population     float64
AveOccup       float64
Latitude       float64
Longitude      float64
MedHouseVal    float64
dtype: object

In [10]:
data[:4]

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413

In [13]:
data.iloc[:4,-2:]

Longitude  MedHouseVal
0    -122.23        4.526
1    -122.22        3.585
2    -122.24        3.521
3    -122.25        3.413

## Podział danych

### Podział prosty

Do dokonania podziału prostego przeznaczona jest funkcja *train_test_split* znajdująca się w module *model_selection* pakietu *sklearn*. Najważniejsze parametry przyjmowane przez funkcję to:
- (nienazwane) tablice NumPy z atrybutami warunkowymi oraz opcjonalnie z atrybutem decyzyjnym,
- test_size: odsetek stanowiący rozmiar danych testowych,
- random_state: ziarno losowości. Pozwala nam na "stały" podział zbioru, tzn. każde wykonanie kodu z tym samym ziarnem da taki sam efekt.

Wynikiem funkcji będą dwie (dla jednej przekazanej tablicy wejściowej z danymi- tylko cechy) lub cztery (dla dwóch tablic wejściowych- cechy i klasy) tablice stanowiące podział danych wejściowych na dane treningowe i testowe.

In [16]:
from sklearn.model_selection import train_test_split
import numpy as np

Podział prosty atrybutów warunkowych można przeprowadzić przekazując tylko jedną tablicę wejściową. Podział zostanie przeprowadzony w stosunku 80%:20% odpowiednio dla podzbioru treningowego i testowego. Parametr *test_size* określamy w liczbie zmiennoprzecinkowej w zakresie (0,1), która określa wielkość zbioru testowego- tj. 0.2 oznacza, że zbiór testowy będzie zawierał 20% wielkości zbioru wejściowego.

In [17]:
X = np.arange(80).reshape((20, 4))  # tablica zawierajace atrybuty warunkowe
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79]])

In [28]:
X_train, X_test = train_test_split(X, test_size=0.2)
print(X_train, X_test, sep="\n===============\n")

[[48 49 50 51]
 [52 53 54 55]
 [ 8  9 10 11]
 [40 41 42 43]
 [32 33 34 35]
 [68 69 70 71]
 [64 65 66 67]
 [56 57 58 59]
 [ 4  5  6  7]
 [16 17 18 19]
 [ 0  1  2  3]
 [76 77 78 79]
 [12 13 14 15]
 [28 29 30 31]
 [24 25 26 27]
 [60 61 62 63]]
[[44 45 46 47]
 [36 37 38 39]
 [20 21 22 23]
 [72 73 74 75]]


In [31]:
X_train, X_test = train_test_split(X, test_size=0.2, random_state=39)
print(X_train, X_test, sep="\n===============\n")

[[28 29 30 31]
 [48 49 50 51]
 [68 69 70 71]
 [40 41 42 43]
 [ 4  5  6  7]
 [32 33 34 35]
 [60 61 62 63]
 [64 65 66 67]
 [44 45 46 47]
 [12 13 14 15]
 [24 25 26 27]
 [16 17 18 19]
 [ 0  1  2  3]
 [72 73 74 75]
 [76 77 78 79]
 [36 37 38 39]]
[[ 8  9 10 11]
 [56 57 58 59]
 [52 53 54 55]
 [20 21 22 23]]


In [34]:
len(X), len(X_train), len(X_test)
assert len(X) == len(X_train) + len(X_test)
# assert len(X) == len(X_train) + len(X_test) + 1

Dla atrybutów warunkowych i atrybutu decyzyjnego podział ten można przeprowadzić analogicznie dodając do funkcji kolejny zbiór.

In [35]:
X = np.arange(80).reshape((20, 4))  # tablica zawierajace atrybuty warunkowe
y = range(20)  # tablica zawierajaca jeden atrybut decyzyjny
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=39)

In [36]:
print(X_train, X_test, y_train, y_test, sep="\n===============\n")

[[28 29 30 31]
 [48 49 50 51]
 [68 69 70 71]
 [40 41 42 43]
 [ 4  5  6  7]
 [32 33 34 35]
 [60 61 62 63]
 [64 65 66 67]
 [44 45 46 47]
 [12 13 14 15]
 [24 25 26 27]
 [16 17 18 19]
 [ 0  1  2  3]
 [72 73 74 75]
 [76 77 78 79]
 [36 37 38 39]]
[[ 8  9 10 11]
 [56 57 58 59]
 [52 53 54 55]
 [20 21 22 23]]
[7, 12, 17, 10, 1, 8, 15, 16, 11, 3, 6, 4, 0, 18, 19, 9]
[2, 14, 13, 5]


In [37]:
len(X_train), len(y_train), len(X_test), len(y_test)

(16, 16, 4, 4)

Przeprowadźmy test- wygenerujmy przykładowe dane gotowe do klasyfikacji binarnej (tj. klasyfikacja, gdzia argue\ment decyzyjny jedynie wskazuje bądź nie przynależność do jednej z dwóch klas) i podzielmy dane poznaną metodą.

In [79]:
X = np.arange(400).reshape((100, 4))  # tablica zawierajace atrybuty warunkowe
y = np.array([0] * 50 + [1] * 50)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(y_train, y_test, sep="\n===============\n")

unique, counts = np.unique(y_test, return_counts=True)
for value, count in zip(unique, counts):
    print(f"Wartość {value} występuje {count} razy")

[0 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0
 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 1
 1 1 1 0 1 0]
[0 1 1 0 0 0 1 1 0 1 1 1 0 1 0 0 1 0 1 1]
Wartość 0 występuje 9 razy
Wartość 1 występuje 11 razy


Przeprowadźmy kolejny eksperyment. Co w przypadku, gdy dane nie są równorozłożone pomiędzy klasy?

In [115]:
X = np.arange(400).reshape((100, 4))  # tablica zawierajace atrybuty warunkowe
y = np.array([0] * 20 + [1] * 80)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(y_train, y_test, sep="\n===============\n")

unique, counts = np.unique(y_test, return_counts=True)
for value, count in zip(unique, counts):
    print(f"Wartość {value} występuje {count} razy")

[0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 1
 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1
 1 0 1 1 1 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
Wartość 0 występuje 2 razy
Wartość 1 występuje 18 razy


Zmniejszmy teraz wielkość zbioru testowego do 10% i zobaczmy jak zareaguje nasz kod.

In [137]:
X = np.arange(400).reshape((100, 4))  # tablica zawierajace atrybuty warunkowe
y = np.array([0] * 20 + [1] * 80)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(y_train, y_test, sep="\n===============\n")

unique, counts = np.unique(y_test, return_counts=True)
for value, count in zip(unique, counts):
    print(f"Wartość {value} występuje {count} razy")

[1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 0 0 0 1 1 1
 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1]
[1 1 1 1 1 1 1 1 1 1]
Wartość 1 występuje 10 razy


W pewnym skrajnym przypadku występuje dość specyficzny przypadek- w zbiorze testowym występuje tylko i wyłącznie jedna z klas- 1 bądź 0 i ilość wystąpień tej klasy jest równoliczna z wielkością zbioru testowego.

Warto zatem zauważyć, że istotną wadą podziału prostego jest brak zachowania proporcji względem wybranego atrybutu. Przykładowo, jeżeli w atrybucie decyzyjnym znajdzie się dziesięć zer i dziesięć jedynek, nie mamy kontroli nad tym czy w podzbiorze testowym (o rozmiarze 4) znajdą się same zera, czy dwa zera i dwie jedynki, co jest proporcją zgodną z pełnym oryginalnym zbiorem danym.

### Podział warstwowy

W bibliotece scikit-learn znajduje się klasa *StratifiedShuffleSplit*, której przeznaczeniem jest dokonywanie wielokrotnych podziałów z zachowaniem proporcji występujących w oryginalnej populacji. Inicjalizator klasy *StratifiedShuffleSplit* przyjmuje następujące parametry:
- n_splits: liczba podziałów,
- test_size: odsetek obiektów stanowiących podzbiór testowy,
- random_state: ziarno losowości.

Na obiekcie klasy *StratifiedShuffleSplit* jest dostępna metoda *split*, która przyjmuje parametry w postaci tablicy zawierającej zestaw atrybutów warunkowych oraz tablicy z atrybutem decyzyjnym. Wynikiem funkcji jest iterator, po którym można przeiterować się za pomocą pętli for. Liczba przebiegów będzie zgodna z wartością parametru *n_splits* inicjalizatora klasy *StratifiedShuffleSplit*, a w każdym przebiegu pętli obiekt sterujący będzie stanowiła krota zawierająca dwa elementy: tablicę indeksów obiektów z oryginalnego zbioru danych stanowiącego podzbiór treningowy oraz testowy.


Na potrzeby przykładu wygenerujemy nowy atrybut decyzyjny, który będzie zawierał wartości 0 i 1 w proporcji 50%:50%.

In [138]:
data_size = len(data)
half_data_size = data_size // 2
data['decision'] = np.array([0] * half_data_size + [1] * half_data_size)

In [139]:
from sklearn.model_selection import StratifiedShuffleSplit

In [216]:
splitter = StratifiedShuffleSplit(n_splits=10, test_size=0.2)
output_col = 'decision'

for train_index, test_index in splitter.split(data.loc[:, data.columns != output_col], data[output_col]):
    train_data, test_data = data.loc[train_index,output_col], data.loc[test_index,output_col]

unique, counts = np.unique(train_data, return_counts=True)
for value, count in zip(unique, counts):
    print(f"Wartość {value} występuje {count} razy")
    
unique, counts = np.unique(test_data, return_counts=True)
for value, count in zip(unique, counts):
    print(f"Wartość {value} występuje {count} razy")

Wartość 0 występuje 8256 razy
Wartość 1 występuje 8256 razy
Wartość 0 występuje 2064 razy
Wartość 1 występuje 2064 razy


## Zadania

Zadania odsyłamy w wyznaczonym do tego miejscu na Classromie zajęć w terminie do następnych zajęć (uprzedzając pytania - tak co do godziny). Zadania im wcześniej zostaną przesłane, tym wcześniej zostaną ocenione. *Zadania z błędami należy poprawić.* **Zadania odesłane po terminie nie będą oceniane.**

1. Przygotować funkcję get_dataset(name: str) -> pd.DataFrame, która zwróci ramkę danych z wczytanym zbiorem danych dostępnym w pakiecie Scikit-learn. Jako nazwę można przyjąć dowolny identyfikator, np. alias w adresie URL prowadzącym do szczegółów zbioru: https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset (alias jest dostępny po znaku #).

2. Dokonać podziału podzbioru treningowego w stosunku 80%:20% przeznaczając 20% na podzbiór walidacyjny, gdzie pozostałe 80% nadal będzie stanowiło podzbiór treningowy, lecz okrojony.

3. Dla przeprowadzonych podziałów metodą prostą oraz warstwową (dla każdego podziału) przygotować histogram prezentujący rozkład liczebności wartości atrybutu decyzyjnego zarówno w podzbiorze treningowym, jak i testowym.

4. Dokonać podziału oryginalnego zbioru danych metodą warstwową względem innego atrybutu (obecnego w pierwotnej wersji zbioru). Jakiego atrybutu i dlaczego warto użyć? Dopuszczalne są niewielkie i uzasadnione zmiany wartości atrybutu stanowiącego źródło proporcji podziału.